version: "3"

services:
    "movieservice":
      build:
        context: .
        dockerfile: Dockerfile
        args:
          buildno: 1
      image: movieserviceimg:latest
      container_name: movieservice
      ports:
        - 8085:8081
      links:
        - mongo
      depends_on:
        - mongo


    "mongo":
      image: mongo
      container_name: mongo
      ports:
        - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet







