---

spring:
  profiles:
    active: dev
app:
  name: movieservice
  description: ${app.name} is a Rest API to provide the movies list
welcome:
  message: welcome to ${app.name}

server:
  port: 8081
  servlet:
    context-path: /movies

---

spring:
  profiles: dev


---

spring:
  profiles: prod

