---

spring:
  profiles:
    active: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: moviedb
#       host: ds241977.mlab.com
#       port: 41977
#       database: CloudFoundry_herkf7ii_vrqbqmdn
#       username: movieuser
#       password: moviepassword
#        uri: mongodb://movieuser:moviepassword@ds241977.mlab.com:41977/CloudFoundry_herkf7ii_vrqbqmdn?ssl=true&authSource=admin&authMechanism=SCRAM-SHA-1

app:
  name: movieservice
#  description: ${app.name} is a Rest API to provide the movies list
#welcome:
#  message: welcome to ${app.name}

server:
  port: 8081
  servlet:
    context-path: /movies

---

spring:
  profiles: dev


---

spring:
  profiles: prod

